import wealthAccount_en from './wealthAccount_en'

export default {
    // Titles
    wealth: 'Wealth Management',
    fundDetail: 'Fund Details',
    holdingDetails: 'Holdings Details',

    // Wealth Homepage
    riskTipExpired:
        'Your risk assessment result has expired. To ensure your investment activities are not affected, please complete a new assessment as soon as possible',
    openFundAccount: 'Open Wealth Account',
    updateFundAccount: 'Upgrade Wealth Account',
    openManagerAssets: 'Start Your Wealth Management Journey',
    updateManagerAssets: 'Enjoy More Privileges After Upgrade',
    openAccountNow: 'Open Account Now',
    otherProduct: 'View Other Products',
    notTradable: 'This product is currently not available for trading',

    // Important Information
    importantInfo: 'Important Information and Declarations',
    cashBox: 'Star Cash Box',
    cashManage: 'Cash Management',
    stableInvest: 'Bond Funds',
    advancedInvest: 'Equity Funds',
    privatePlacement: 'Private Funds',
    bond: 'Bonds',
    insurance: 'Insurance',
    alterInvestment: 'Bills',
    starTreasureSpecial: 'Star Cash Box Special Account',
    fundRelationCompanyTip: 'Wealth management services provided by',
    fundRelationCompany: 'Fosun International Securities',
    provide: 'provide',

    // Holdings Homepage
    accountHoldTitle: 'Account Holdings',
    orderRecord: 'Order Records',
    riskAssessment: 'Risk Assessment',
    myHoldings: 'My Holdings',
    myHoldings1: 'My Holdings',
    detail: 'Details',
    subscribe: 'Buy',
    redeem: 'Sell',
    recall: 'Cancel',
    fundName: 'Fund Name',
    marketValue: 'Market Value',
    count: 'Quantity',
    accumulatedProfit: 'Accumulated Profit',
    accumulatedRate: 'Accumulated Return Rate',
    floatprofit: 'Floating P/L',
    noHold: 'No Holdings',
    profitDesc: 'Profit Description',

    // Asset Card
    totalAssets: 'Net Asset Value',
    yesterdayProfit: "Yesterday's Profit",
    cashBalance: 'Cash Balance',
    onlineAsset: 'In-Transit Assets',

    // Matching Page
    productName: 'Product Name',
    matchRes: 'Matching Result',
    productInfo: 'Product Information',
    product: 'Product',
    me: 'Me',
    isMatch: 'Match Status',
    restartRiskAssessment: 'Reassess',
    derivativeInfo: 'Derivatives Knowledge',
    riskLevel: 'Risk Level',
    investTarget: 'Investment Objective',
    investExperience: 'Investment Experience',
    match: 'Match',
    noMatch: 'No Match',
    need: 'Required',
    noNeed: 'Not Required',

    // Risk Levels
    lowRisk: 'Low Risk',
    middleLowRisk: 'Medium-Low Risk',
    middleRisk: 'Medium Risk',
    middleHighRisk: 'Medium-High Risk',
    highRisk: 'High Risk',

    // Investment Objectives
    dominate: 'Capital Preservation',
    mainlyForIncome: 'Income Focused',
    incomeAndGrowth: 'Income and Growth',
    growthDominance: 'Growth Focused',
    aggressiveGrowth: 'Aggressive Growth',

    // Knowledge and Experience
    unKnow: 'No',
    know: 'Yes',
    steady: 'Conservative',
    moderate: 'Moderate',
    isostasy: 'Balanced',
    growth: 'Growth',
    aggressive: 'Aggressive',

    // Investment Experience
    lessOneYear: 'Less than 1 year',
    oneToFiveYear: '1-5 years',
    sixToTenYear: '6-10 years',
    eveToTwenty: '11-20 years',
    moreTwentyYear: 'More than 20 years',

    // Bills Related
    bills: {
        or: 'or',
        sub: 'Expected Annualized Rate',
        btn: 'View Details',
        verify: 'Visible After Certification',
        verifyToUnlock: '*Complete professional investor certification to view',
        billsDetail: 'Bill Details',
        annualizedYTM: 'Annualized Yield',
        remainingTerm: 'Maturity Date',
        duration: 'Term',
        productIntroduction: 'Product Introduction',
        productFeature: 'Product Features',
        productBenefits: 'Product Benefits',
        mainRisks: 'Key Risks',
        productFiles: 'Product Documents',
        type: 'Type',
        updateTime: 'Update Time',
        tradeRules: 'Trading Rules',
        minInitial: 'Minimum Purchase Amount',
        maxInitial: 'Maximum Purchase Amount',
        unitAmount: 'Unit Amount',
        buyFee: 'Transaction Fee',
        buy: 'Buy',
        buyBill: 'Buy Bill',
        riskLevel: {
            0: 'No Risk',
            1: 'Low Risk',
            2: 'Medium-Low Risk',
            3: 'Medium Risk',
            4: 'Medium-High Risk',
            5: 'High Risk',
        },
        complexProduct: 'Complex Product',
        selectProduct: 'Select Product',
        buyAmount: 'Purchase Amount',
        buyAll: 'Buy All',
        maxAmount: 'Maximum Amount',
        buyFeeRate: 'Purchase Fee Rate',
        estimateCost: 'Estimated Cost',
        accountAmount: 'Available Balance',
        payRate: {
            0: 'None',
            1: '<15%',
            2: '<30%',
            3: '<45%',
            4: '<60%',
            5: '>60%',
        },
        agreeProtocol: 'I have read and agree to ',
        protocols: 'Related Agreement Documents',
        amountPlaceholder: 'Minimum {amount} {currency}',
        productText: 'Matures in {period}, Annualized Rate {yield}',
        productPeriodText: 'Matures on {date}, {period} months',
        profitText: 'Expected Return at Maturity',
        minLimitMsg: 'Minimum investment amount {amount} {currency}',
        maxLimitMsg: 'Exceeds maximum amount {amount} {currency}',
        unitLimitMsg: 'Purchase amount must be in multiples of {amount}',
        startAmount: 'Minimum Investment',
        startAmountValue: '{amount} {currency}, increasing in units of {unitAmount} {currency}',
        selectPlaceholder: 'Please Select',
        prompt: 'Note: Each bill issuance requires a minimum subscription of USD 200,000 to be established. The company reserves the right of final interpretation.',
        customProducts: 'Custom Bill Products',
        myCustomize: 'My Customizations',
        goToCustomize: 'Customize',
        customProductRecords: 'Custom Product Records',
        addCustomizeProduct: 'Add Custom Product',
        yield: 'Yield',
        expiryDate: 'Maturity Date',
        noFinishedProducts: 'No Completed Products',
        customObjects: 'Customization Objects',
        intendedSubscriptionAmount: 'Intended Subscription Amount',
        referenceRates: 'Reference Rates',
        expectedInvestmentPeriod: 'Expected Investment Period',
        chooseInvestmentTips: 'Select investment period to predict annualized rate',
        rateExpectedTips1: 'Based on historical data, ',
        rateExpectedTips2: 'Expected Annualized Rate',
        submit: 'Submit',
        submitAgain: 'Submit Again',
        buyTime: 'Purchase Time',
        confirmDeadline: 'Confirmation Deadline',
        confirmDeadlineTips: 'If not confirmed by the deadline, the custom product will be automatically rejected',
        accept: 'Accept',
        acceptAndBuy: 'Accept and Buy',
        refuse: 'Reject',
        englishName: 'English Name',
        estimatedReleaseTime: 'Estimated Issue Date',
        settlementDate: 'Settlement Date',
        submitTips: 'Bill customization request submitted, please wait patiently for order processing',
        intendedPurchaseAmount: 'Intended Purchase Amount',
        submitTime: 'Submission Time',
        canceled: 'Cancelled',
        rejected: 'Rejected',
        customizeResult: 'Customization Result',
        guarantor: 'Guarantor',
        specifyCurrency: 'Specified Currency',
        expirationDeliveryDate: 'Product Maturity Delivery Date',
        accrueDays: 'Interest Accrual Days',
        productRiskLevel: 'Product Risk Level',
        modify: 'Modify',
        noCustomize: 'No Further Customization',
        confirmRefuseCustomizeTips: 'Confirm rejection of customized product? Please select rejection type',
        confirmCustomizeTips: 'Confirm cancellation of customized product?',
        customConfirmTips:
            'The above content is for reference only and this transaction is subject to the terms and conditions of the final confirmation document. If you agree to the above content, please arrange the deposit as soon as possible. Before confirming the order, Fosun International Securities Limited ("Fosun International Securities") reminds you of the relevant risks of this product.',
        pending: 'Pending',
        declined: 'Declined',
        floatRateText: 'Reference Rate (Annualized)',
        cancelCustomizeTips: 'Do you want to cancel this customized product?',
        success: 'Success',
        rejectionReasons: 'Rejection Reasons: ',
        noOrdersText: 'No Order Records',
        simplifiedName: 'Simplified Chinese Name',
        traditionalName: 'Traditional Chinese Name',
        englishLabel: 'English Label',
        simplifiedLabel: 'Simplified Chinese Label',
        traditionalLabel: 'Traditional Chinese Label',
        settlementDateCN: 'Settlement Date (Simplified)',
        settlementDateTC: 'Settlement Date (Traditional)',
        settlementDateEN: 'Settlement Date (English)',
        paymentDueCN: 'Payment Due (Simplified)',
        paymentDueTC: 'Payment Due (Traditional)',
        paymentDueEN: 'Payment Due (English)',
        customizeProduct: 'Customize Product',
        expectedRatio: 'Expected Annualized Rate',
        calculatDayScores: 'Day Count Fraction',
        floatingInterest: 'Floating Interest',
        haveCustomizeErrorTips: 'A customization request already exists. Please wait for processing results or view and modify.',
        customizeRecords: 'Customization Records',
        billCustomizeAdd: 'Create New Custom Bill Product',
        billCustomizeEdit: 'Modify Custom Bill Product',
        changeProductInfo: 'Product Information Change',
        openDerivativesPermissionsTips:
            'Derivatives include but are not limited to derivative warrants, CBBCs, stock/index futures and options, structured commodity products and ETFs, whether traded on exchanges or not.',
        openFundAccountTips:
            'After opening a wealth account, you can purchase OTC funds, OTC bonds, bills and other products; without a wealth account, you cannot purchase these products.',
        openDerivativesPermissions: 'Enable Derivatives Trading',
        referenceRate: 'Reference Rate',
        referenceRateCN: 'Reference Rate (Simplified)',
        referenceRateTC: 'Reference Rate (Traditional)',
        referenceRateEN: 'Reference Rate (English)',
        confirmedTips: 'Accepted, please wait patiently for order processing results',
        customizeDetail: 'Customization Details',
        pleaseInput: 'Please enter bill name/ISIN code',
        pleaseInput2: 'Please select linked underlying name/code',
        referenceRange: 'Target Reference Yield Range',
    },

    // Fund Details Page
    deleteSelf: 'Remove from Watchlist',
    addSelf: 'Add to Watchlist',
    piTip: 'You are not yet certified as a professional investor. Please contact your account manager to view product details.',
    iKnow: 'I Understand',
    tipTitle: 'Tips',
    performance: 'Performance',
    performanceTrend: 'Performance Trend',
    selfFund: 'This Fund',
    sameAverage: 'Category Average',
    holding: 'Holdings',
    analysis: 'Analysis',
    profile: 'Profile',
    rule: 'Rules',
    classify: 'Category',
    profit: 'Return',
    assetSize: 'Asset Size',
    updateTime: 'Updated: ',
    currency: 'Currency: ',
    dividend: 'Dividend',
    noDividend: 'No Dividend',

    // Fund Related
    selectedStar: 'Star Selection',
    nearThreeYearIncome: '3-Year Return',
    buyNow: 'Buy Now',
    aggressiveInvest: 'Aggressive Investment',
    starSelectedPublicFund: 'Star Selected Public Fund',
    nearThreeYearIncomeRate: '3-Year Return Rate',
    stableIncome: 'Stable Income',
    sevenDayIncome: '7-Day Annualized Yield',

    // Fund Types
    stockType: 'Equity',
    bondType: 'Fixed Income',
    mixedType: 'Mixed',
    mixed: 'Mixed',
    currencyType: 'Money Market',
    nationalBond: 'Government Bond',
    governmentBond: 'Government Bond',
    corporateBond: 'Corporate Bond',
    stockRightType: 'Equity',

    // Risk and Product Info
    riskWarning: 'Risk Warning',
    complexProduct: 'Complex Product',
    publicFund: 'Public Fund',
    privateFund: 'Private Fund',
    nearThreeChg: '3-Month Change',
    nearOneYearChg: '1-Year Change',
    latestNet: 'Latest NAV',
    starRating: 'Morningstar Rating',
    noStar: 'No Rating',

    // Fund Performance
    historyNet: 'Historical NAV',
    historyProfit: 'Historical Return',
    annualProfit: 'Annual Return',
    historyPeriod: 'Period',
    date: 'Date',
    currencyNet: 'NAV',
    dayChg: 'Daily Change',

    // Time Periods
    nearOneDay: '1 Day',
    nearOneWeek: '1 Week',
    nearOneMonth: '1 Month',
    nearThreeMonth: '3 Months',
    nearSixMonth: '6 Months',
    nearOneYear: '1 Year',
    nearTwoYear: '2 Years',
    nearThreeYear: '3 Years',
    nearFourYear: '4 Years',
    nearFiveYear: '5 Years',
    yearToDay: 'YTD',
    fromFoundedToDay: 'Since Inception',

    // Rankings and Performance
    investmentIncome: 'Investment Return',
    weeklyLeaderboard: 'Weekly Ranking',
    monthlyLeaderboard: 'Monthly Ranking',
    quarterlyLeaderboard: 'Quarterly Ranking',
    halfYearLeaderboard: 'Half-Year Ranking',
    yearLeaderboard: 'Annual Ranking',
    threeYearLeaderboard: '3-Year Ranking',
    totalLeaderboard: 'Total Return Ranking',
    followLeaderboard: 'Following Ranking',

    // Portfolio Analysis
    fundHolding: 'Fund Holdings',
    noQuoteData: 'No Market Data Available',
    investCompose: 'Portfolio Composition',
    assetType: 'Asset Type',
    industryDistribute: 'Industry Distribution',
    marketDistribute: 'Market Distribution',
    noMarketDistribute: 'No Market Distribution Data',
    areaDistribute: 'Geographic Distribution',
    bondCredit: 'Bond Credit Rating',

    // Investment Style
    investStyleBox: 'Investment Style Box',
    currentStyle: 'Current Style: ',
    size: 'Size',
    style: 'Style',
    largeBoard: 'Large Cap',
    midBoard: 'Mid Cap',
    smallBoard: 'Small Cap',
    valuation: 'Value',
    blend: 'Blend',
    growthStyle: 'Growth',

    // Additional Classifications
    moreClassify: 'More Categories',
    classifyTip: 'Class-A shares enjoy fixed target returns,\nClass-B shares provide capital protection for Class-A shares',
    iGet: 'I Understand',

    // Fund Profile
    fundProfile: 'Fund Profile',
    name: 'Name',
    presidency: 'Tenure',
    type: 'Type',
    updateDate: 'Update Date',
    isinCode: 'ISIN Code',
    classOfShares: 'Share Class',
    fundType: 'Fund Type',
    baseType: 'Base Type',
    foundPosition: 'Domicile',
    fundFoundDay: 'Fund Inception Date',
    foundDay: 'Inception Date',
    typeDate: 'Class Inception Date',
    custodianCompany: 'Custodian',
    baseCurrency: 'Base Currency',
    tradingFrequency: 'Trading Frequency',
    minInitial: 'Minimum Investment',
    fundBrief: 'Fund Description',
    lockPeriod: 'Lock-up Period',
    fundManager: 'Fund Manager',
    fundFile: 'Fund Documents',
    soFar: 'To Date',

    // Risk Indicators
    riskIndicator: 'Risk Indicators',
    indicator: 'Indicator',
    maxDrawDown: 'Maximum Drawdown',
    rSquare: 'R-Square',
    sharpRate: 'Sharpe Ratio',
    returnYear: 'Annualized Return',
    averageReturnYear: 'Average Annualized Return',
    stdDeviationYear: 'Annualized Standard Deviation',
    deviationYear: 'Standard Deviation',

    // Trading Rules
    tradeRule: 'Trading Rules',
    tradeProcess: 'Trading Process',
    fee: 'Fees',
    buyRightNow: 'Buy Now',
    cost: 'Costs',
    firstProfitCome: 'First Return Payment',
    subscribeProcess: 'Subscription Process',
    redeemProcess: 'Redemption Process',

    // Order Related
    yiquerenfene: 'Confirmed Units',
    xiadanshibai: 'Order Failed',
    fangxiangzhuangtai: 'Type/Status',
    jinefene: 'Amount/Units',
    xdsj: 'Order Time',
    shaixuan: 'Filter',
    riqishaixuan: 'Date Filter',
    xuanzenianyueri: 'Select Date',
    chongzhi: 'Reset',
    wancheng: 'Complete',
    queren: 'Confirm',
    leixing: 'Type',
    zhuangtai: 'Status',
    chedannofee: 'No subscription fee will be charged for cancellation',
    bizhong: 'Currency',
    ddje: 'Order Amount',
    weituoleixing: 'Order Type',
    shuhuifei: 'Redemption Fee',
    dingdanhao: 'Order Number',
    withdraw: 'Withdraw',
    qrysh: 'Confirm withdrawal',
    ma: '?',
    refreshStatus: 'Refresh Status',

    // Trading Related
    yquerenfene: 'Confirmed Units',
    yquerenjine: 'Confirmed Amount',
    dingdanzhuangtai: 'Order Status',
    dingdanleixing: 'Order Type',
    caozuo: 'Operation',
    xiadanshijian: 'Order Time',
    querenriqi: 'Confirmation Date',
    jiaoyiriqi: 'Trading Date',
    jiaoyishijian: 'Trading Time',
    jiaoyileixing: 'Trading Type',
    jiaoyizhuangtai: 'Trading Status',
    mairujiage: 'Purchase Price',
    mairujine: 'Purchase Amount',
    mairushuliang: 'Purchase Quantity',
    maichushuliang: 'Sell Quantity',
    maichujine: 'Sell Amount',
    mairufene: 'Purchase Units',
    maichufene: 'Sell Units',

    // Additional Trading Terms
    jiaoyifene: 'Trading Units',
    jiaoyijiage: 'Trading Price',
    jiaoyijine: 'Trading Amount',
    shouxufei: 'Commission Fee',
    qitafeiyong: 'Other Fees',
    zongfeiyong: 'Total Fees',
    zongjine: 'Total Amount',
    keyongyue: 'Available Balance',
    keyongshuliang: 'Available Quantity',
    zuidixianshou: 'Minimum Subscription',
    zuidishuliang: 'Minimum Quantity',
    zuixiaomairujine: 'Minimum Purchase Amount',
    zuixiaomaichujine: 'Minimum Sell Amount',

    // Additional Status and Messages
    zhixingjieguo: 'Execution Result',
    zhixingzhuangtai: 'Execution Status',
    shenqingshijian: 'Application Time',
    shenqingriqi: 'Application Date',
    shenqingleixing: 'Application Type',
    shenqingzhuangtai: 'Application Status',
    tijiaochenggong: 'Submission Successful',
    tijiaoshibai: 'Submission Failed',
    caozuochenggong: 'Operation Successful',
    caozuoshibai: 'Operation Failed',

    // Error Messages and Validations
    qingshurushuliang: 'Please enter quantity',
    qingshurujiage: 'Please enter price',
    qingshurujine: 'Please enter amount',
    bunengweikong: 'Cannot be empty',
    zuidazhi: 'Maximum value',
    zuixiaozhi: 'Minimum value',
    bunengyuling: 'Cannot be zero',
    zhengshuzhi: 'Integer value',
    xiaoshudianhou: 'Decimal places',
    xiaoshushu: 'Decimal number',
    zhengfu: 'Positive/Negative',

    // Additional UI Elements
    quanbu: 'All',
    qita: 'Other',
    zanwushuju: 'No Data',
    jiazaizhong: 'Loading',
    jiazaiwanbi: 'Loading Complete',
    jiazaishibai: 'Loading Failed',
    meiyougengduo: 'No More Data',
    gengduo: 'More',
    yigengxin: 'Updated',

    // Bond Related
    bondTips: 'Bond Order Tips',
    waitConfirm: 'Amendment Pending Confirmation',
    oneDay: 'Valid for Today',
    useless: 'Invalid',
    seconds: 'sec',
    minutes: 'min',
    inFund: 'Deposit Funds',
    orderInTips:
        'Your order price differs from market price and cannot be executed. Would you like to modify the order to the best bid price to expedite matching?',
    orderOutTips:
        'Your order price differs from market price and cannot be executed. Would you like to modify the order to the best ask price to expedite matching?',
    bondName: 'Bond Name',
    applyPrice: 'Order Price',
    filledInPrice: 'Best Bid Price',
    filledOutPrice: 'Best Ask Price',
    refYieldRate: 'Reference Yield Rate',
    validTime: 'Validity Period',
    cancelOrder: 'Cancel Order',
    cancel: 'Cancel',
    wait: 'Wait',
    changeInPrice: 'Modify to Best Bid',
    changeOutPrice: 'Modify to Best Ask',
    changeSuccess: 'Amendment Successful     Pending Trader Confirmation',
    operateSuccess: 'Operation Successful     Trader Notified',
    fundShortage: 'Insufficient available funds for amendment, need additional',

    // Risk Assessment
    noRisk: 'You have not completed risk assessment. To ensure your investment activities are not affected, please complete the assessment as soon as possible',
    confirmDate: 'Confirmation Date',
    filledDate: 'Settlement Date',
    filledPrice: 'Execution Price',
    subscribeFund: 'Subscribe Fund',
    redeemFund: 'Redeem Fund',
    qhdzdb: '(Please scroll to bottom)',
    wyydbqr: 'I have read and confirmed',

    // Product Status
    cantSubscribeFund: 'This product is currently suspended for subscription',
    onlySubscribeFund: 'This product only supports subscription, not redemption',
    onlyRedeemFund: 'This product only supports redemption, not subscription',
    lackQuantity: 'Limited subscription quota available',
    emptyQuantity: 'Subscription quota exhausted',
    estimateCost: 'Estimated Costs',
    confirmPrice: 'Confirmation NAV',
    noQuantityForService: 'Insufficient quota for subscription. For inquiries, please ',

    // Cancel Order
    cancelTip: 'Cancellation Notice',
    cancelRemindDesc: 'Please confirm cancellation. This action cannot be undone',
    tradeDirection: 'Trade Direction',
    transactDate: 'Transaction Time',
    transactQuantity: 'Transaction Quantity',
    transactAverage: 'Average Price',
    transactAmount: 'Transaction Amount',
    entrustQuantity: 'Order Quantity',
    entrustPrice: 'Order Price',
    entrustAmount: 'Order Amount',
    confirmCashBoxBankWithdarw: 'Cancelling this sell order will also cancel the associated withdrawal request. Please confirm cancellation',

    // Profit and Details
    profitDetail: 'Profit Details',
    orderDetail: 'Order Details',
    riskMatchTitle: 'Suitability Matching',
    shouyijilu: 'Profit Records',
    zsjsgyjl: 'Showing last 3 months records',
    allFund: 'All Funds',
    insuranceDetail: 'Insurance Details',
    brief: 'Brief',
    specialAdvantage: 'Features and Advantages',

    // Risk Assessment
    noMatchDes:
        'Suitability check reveals: This product has mismatched items with your risk tolerance. According to investor suitability regulations, you cannot purchase products exceeding your risk tolerance.',
    noMatchDes_:
        'If you believe your previous risk assessment results do not match your actual situation, please click "View Reason" to check matching records and reassess.',
    productDemand: 'Investment concentration limit requirement for this product',
    cancelBuy: 'Cancel Purchase',

    // Legal Disclaimers
    billLegalTip: 'Investment involves risks. Please read the offering documents carefully before investing.',
    customBillListLegalTip2: 'This product is only available to Professional Investors',

    // Additional Product Information
    ygSellingCosts: 'Estimated Selling Costs',

    // Risk Analysis
    riskAnalysis: {
        title: 'Risk Analysis',
        h1: 'R-Square',
        text1: "Indicates how well the fund's returns correlate with the benchmark index. The closer to 1, the more similar the fund's performance to the benchmark.",
        h2: 'Beta',
        text2: "Measures the fund's volatility relative to the market. Beta > 1 indicates higher volatility than the market; Beta < 1 indicates lower volatility.",
        h3: 'Maximum Drawdown',
        text3: 'Shows the maximum decline in fund value from peak to trough. Generally, a smaller absolute value is better, indicating better risk control.',
        h4: 'Sharpe Ratio',
        text4: 'Indicates excess return per unit of risk (standard deviation). Generally, a higher Sharpe ratio is better, showing better risk-adjusted returns. A ratio > 1 means returns exceed volatility risk; < 1 means volatility risk exceeds returns.',
        h5: 'Calmar Ratio',
        text5: 'Shows excess return per unit of risk (maximum drawdown). Generally, a higher ratio is better, indicating better risk-adjusted returns. Best used for comparing similar funds.',
    },

    // Insurance Related
    insuranceProfit: {
        title: 'Savings Participating Insurance',
        'biref-text1':
            'Savings participating insurance is a type of insurance that provides both protection and dividend benefits. In Hong Kong, the cash value of whole life savings participating insurance is divided into "guaranteed" and "non-guaranteed" portions. This means that the most important aspect of Hong Kong savings participating insurance is the dividend level, which depends on the long-term performance of the insurance company.',
        'special-text1': '1. Lower life protection component;',
        'special-text2': '2. Premium payment periods are mainly 5 or 10 years;',
        'special-text3': '3. Guaranteed returns are generally low, around 2-3%;',
        'special-text4': '4. Non-guaranteed returns depend on company performance;',
        'special-text5': '5. Suitable for long-term wealth accumulation.',
    },

    // Critical Illness Insurance
    insuranceSick: {
        title: 'Critical Illness Insurance',
        'biref-text1':
            'Critical illness insurance generally provides protection for specific serious illnesses such as cancer, stroke, heart disease and other health threats. For most people, social medical insurance can cover minor illnesses; but in case of critical illness, commercial critical illness insurance can provide substantial compensation to help the insured person overcome life difficulties and provide living security for a period of time.',
        'biref-text2':
            'In terms of effective period, critical illness insurance can be divided into term and whole life types. Whole life critical illness insurance refers to critical illness insurance with savings function, having both "savings" and "protection" features.',
        'special-text1':
            '1. Lower premiums. Compared to mainland insurance, Hong Kong insurance premiums are 30% cheaper under the same conditions (sum assured, age, payment period, smoking status, etc.).',
        'special-text2':
            '2. More comprehensive coverage. Hong Kong critical illness insurance generally covers more illnesses, with some products covering over 168 illnesses. Early-stage carcinoma in situ is covered with minor illness benefits, and most policies offer 3 multiple claims with additional protection for high-risk diseases like heart disease and stroke.',
        'special-text3':
            '3. Participating sum assured. While most mainland insurance policies have fixed sum assured, Hong Kong policies are participating, which helps offset inflation to some extent.',
        'special-text4':
            '4. More lenient claims. Contract terms define illnesses more broadly in Hong Kong insurance, making claims much more lenient compared to mainland policies, especially for high-incidence diseases.',
    },

    insuranceLife: {
        title: 'Term Life Insurance',
        'biref-text1':
            'Life insurance is mainly divided into two categories: Term Life Insurance that provides protection for a specific period and Whole Life Insurance that provides lifelong protection.',
        'biref-text2':
            'Term life insurance provides pure life protection without savings component, offering relatively high coverage at affordable premiums, with fixed protection/renewal periods. Premiums are adjusted based on age after each renewal period.',
        'special-text1':
            '1. Comprehensive planning, complete protection. Clients can choose death benefit payment methods - lump sum, installments, or a combination, providing flexibility in asset allocation.',
        'special-text2':
            '2. Affordable premiums, personalized options. Provides high life coverage at affordable premiums with flexible renewal periods, allowing clients to choose suitable renewal terms based on short or medium-term protection needs.',
        'special-text3':
            "3. Additional protection, extra peace of mind. If the insured is certified by a registered professional doctor as likely to pass away within 12 months, the policy will provide advance death benefit payment to help the client's family through difficult times.",
    },

    // Additional Fund Features
    fundFeatures: {
        fundStrategy: 'Investment Strategy',
        investmentObjective: 'Investment Objective',
        investmentUniverse: 'Investment Universe',
        investmentProcess: 'Investment Process',
        riskManagement: 'Risk Management',
        portfolioConstruction: 'Portfolio Construction',
        researchCapabilities: 'Research Capabilities',
        teamExperience: 'Team Experience',
        trackRecord: 'Track Record',
        competitiveAdvantage: 'Competitive Advantage',
    },

    // Fund Ratings
    fundRatings: {
        morningstarRating: 'Morningstar Rating',
        morningstarCategory: 'Morningstar Category',
        morningstarRisk: 'Morningstar Risk',
        morningstarReturn: 'Morningstar Return',
        sustainabilityRating: 'Sustainability Rating',
        quantitativeRating: 'Quantitative Rating',
        analystRating: 'Analyst Rating',
        ratingDate: 'Rating Date',
        ratingTrend: 'Rating Trend',
        ratingAnalysis: 'Rating Analysis',
    },

    // Fund Costs
    fundCosts: {
        totalExpenseRatio: 'Total Expense Ratio',
        managementFee: 'Management Fee',
        distributionFee: 'Distribution Fee',
        adminFee: 'Administration Fee',
        custodianFee: 'Custodian Fee',
        auditFee: 'Audit Fee',
        registrarFee: 'Registrar Fee',
        otherExpenses: 'Other Expenses',
        ongoingCharges: 'Ongoing Charges',
        performanceFee: 'Performance Fee',
    },

    // Fund Risks
    fundRisks: {
        investmentRisk: 'Investment Risk',
        marketRisk: 'Market Risk',
        currencyRisk: 'Currency Risk',
        creditRisk: 'Credit Risk',
        liquidityRisk: 'Liquidity Risk',
        derivativesRisk: 'Derivatives Risk',
        concentrationRisk: 'Concentration Risk',
        counterpartyRisk: 'Counterparty Risk',
        operationalRisk: 'Operational Risk',
        taxRisk: 'Tax Risk',
    },

    // Fund Operations
    fundOperations: {
        subscriptionDetails: 'Subscription Details',
        redemptionDetails: 'Redemption Details',
        switchingDetails: 'Switching Details',
        distributionDetails: 'Distribution Details',
        valuationDetails: 'Valuation Details',
        settlementDetails: 'Settlement Details',
        cutoffTimes: 'Cut-off Times',
        tradingFrequency: 'Trading Frequency',
        minimumInvestment: 'Minimum Investment',
        subsequentInvestment: 'Subsequent Investment',
    },

    // Bill Related
    billDelayTip:
        'Confirmed bill purchase orders may have delayed display in [Alternative Assets - My Holdings], expected to be synchronized the next day after confirmation',
    productISIN: 'Product ISIN',
    concatService: 'Please contact customer service if product settlement is not completed',
    goBack: 'Back',
    customBillLegalTip:
        'Investment involves risks. Past performance is not indicative of future returns. The price and yield of investment products can go up as well as down. In certain circumstances, investors may lose all their capital. Investors should read the offering documents carefully, including risk factors. You should consider and understand your investment objectives, risk factors and risk tolerance level. If in doubt, you should seek independent financial and professional advice.',
    billListLegalTip:
        'For products described as SFC-authorized complex products, this does not imply official recommendation or endorsement by the SFC, nor does the SFC guarantee the commercial merits or performance of the product.',
    customBillListLegalTip: 'Products are only available to Professional Investors',
    pleaseInputYXJG: 'Please enter target price',
    pleaseInputPMMZ: 'Please enter face value',

    // Portfolio Management
    portfolioFollow: {
        upgradeService: 'Upgrade Advisory Service',
        transferAmount: 'Available Transfer Amount',
        transferAmountMsg: 'Available Transfer Amount = Cash Available for Withdrawal in Main Account',
        notEnoughTransferAmount: 'Exceeds available transfer amount, please deposit funds',
    },

    // Investment Service
    investmentService: {
        investmentStrategyDesc: 'Investment Strategy Description',
        investMarket: 'Investment Market',
        investPrincipal: 'Investment Principal',
        lockPeriod: 'Lock-up Period',
        tradeStrategy: 'Trading Strategy',
        tradeProduct: 'Trading Financial Products',
        valuationCurrency: 'Valuation Currency',
        leverageRatio: 'Leverage Ratio',
        managementAgreement: 'Please refer to the "Discretionary Investment Management Agreement" for specific investment strategy details',
    },

    // Professional Investor
    piVerifyTip1: 'Complete Professional Investor Certification',
    piVerifyTip2: 'View Complete Information',
    order: 'Order',
    teach: 'Investment Education',
    pleaseInputBond: 'Please enter bond name/ISIN code/credit entity',
    professionalInvestorBondNotice: 'This is a Professional Investor Bond. Please complete Professional Investor certification before trading',
    starChoice: 'Star Selection',
    referenceBuy: 'Reference Bid',
    referenceSell: 'Reference Ask',
    referenceDisclaimer:
        'Note: Reference quotes are for price reference only. Due to trading volume, liquidity, and timeliness constraints, trades may not be executed at reference prices',
    yieldToMaturity: 'Yield to Maturity',
    rate: 'Rating',
    couponRate1: 'Coupon Rate',
    sovereignBond: 'Sovereign Bond',
    financeBond: 'Financial Bond',
    cityInvestBond: 'Municipal Investment Bond',
    lowest: 'Lowest',
    highest: 'Highest',
    inputReviseTip: 'Input value unreasonable, automatically revised',

    // Issuer Information
    issuerType: 'Issuer Type',
    issuerIndustry: 'Issuer Industry',
    sovereign: 'Sovereign',
    government: 'Government',
    municipal: 'Municipal',
    supranational: 'Supranational',
    corporate: 'Corporate',
    structuredFinance: 'Structured Finance',
    agency: 'Agency',
    financials: 'Financials',
    consumerGoods: 'Consumer Goods',
    consumerServices: 'Consumer Services',
    energy: 'Energy',
    basicMaterials: 'Basic Materials',
    collectiveInvestmentVehicle: 'Collective Investment Vehicle',
    healthcare: 'Healthcare',
    industrials: 'Industrials',
    technology: 'Technology',
    telecommunicationsServices: 'Telecommunications Services',
    utilities: 'Utilities',
    noResult: 'No Results',
    expired: 'Expired',

    // FCN Related
    fcn: {
        FCNBills: 'FCN Notes',
        InquiryHistory: 'Inquiry History',
        productType: 'Product Type',
        biaodi: 'Underlying',
        objectSelect: 'Select Underlying',
        annualizedCoupon: 'Annualized Coupon',
        strikePrice: 'Strike Price',
        knockOutBid: 'Knock-out Price',
        knockOutObservationFrequency: 'Knock-out Observation Frequency',
        facePar: 'Face Value',
        knockInPrice: 'Knock-in Price',
        time: 'Inquiry Time',
        addEnquiry: 'New Inquiry',
        enquiryDetail: 'Inquiry Details',
        productOptions: 'Product Options',
        observeOptions: 'Observation Options',
        inquiryItem: 'Inquiry Item',
        inquiryPeriod: 'Term (Months)',
        observationFrequency: 'Observation Frequency (Months)',
        inquiryPeriod2: 'Term',
        observationFrequency2: 'Observation Frequency',
        couponFrequency: 'Coupon Frequency',
        coupon: 'Annualized Coupon',
        notePrice: 'Face Value',
        effectiveDateOffset: 'Settlement Time',
        XEffectiveDay: '{X} Calendar Days',
        XEffectiveWorkDay: '{X} Business Days After Trade',
        inquiryType: 'Inquiry Type',
        normalInquiry: 'Regular Inquiry',
        tradeInquiry: 'Trade Inquiry',
        pleaseInput: 'Please Enter',
        error1: 'Only positive integers allowed',
        error2: 'Only positive numbers allowed',
        error3: 'Only numbers within {range} allowed',
        fxfcntips: 'Fosun FCN will only quote when "Trade Inquiry" is selected',
        knockOutType: 'Knock-out Type',
        knockOutObserve: 'Knock-out Observation',
        knockOutType1: 'Final Observation',
        knockOutType2: 'Final Observation (with Memory)',
        knockOutType3: 'Daily Observation',
        knockOutType4: 'Daily Observation (with Memory)',
        perMonthObserve1: 'Every {month} Month Observation',
        perMonthObserve2: 'Every {month} Month Observation (with Memory)',
        perMonthCoupon: 'Periodic Coupon',
        knockInType: 'Knock-in Type',
        knockInType1: 'Not Applicable',
        knockInType2: 'American Knock-in',
        knockInType3: 'European Knock-in',
        inputCannotEmpty: 'Information cannot be empty',
        maxObjectStock: 'Maximum 4 underlyings allowed',
        plsWait: 'Inquiry request submitted, please wait patiently for results',
        InquiryObj: 'Inquiry Object',
        InquiryID: 'Inquiry ID',
        standardProduct: 'Standard Product',
        customBill: 'Custom Note',
        billInquiry: 'Note Inquiry',
        fixInterestBill: 'Star Wealth Fixed Rate Note',
        floatInterestBill: 'Star Wealth Floating Rate Note',
        specialCustomBill: 'Exclusive Custom Note',
        kmhBill1: 'Star Wealth Medium-Long Term Note No.1',
        kmhBill2: 'Star Wealth Medium-Long Term Note No.2',
        kmhBill3: 'Star Wealth Medium-Long Term Note No.3',
        markentingBill: 'Asset/Portfolio Linked Note',
        risk: 'Risk',
        knockOutFrequency: 'Knock-out Observation Frequency',
        offer: 'Quotation Provider',
        quotation: 'Quote',
        monthPeriod: 'Month Term',
        validQuotation: 'Quote Valid Until (HKT): ',
        validSell: 'Sales Period (HKT): ',
        validQuotationExpiration:
            'This quote is for reference only, please obtain latest quote before Hong Kong stock market close on next trading day',
        everyday: 'Daily',
        perMonth: 'Every {month} Month',
        perMonth2: 'Every {month} Months',
        shareListEmpty: 'No products with quotes available',
        quoteResults: 'Quote Results',
        inquiryInfo: 'Inquiry Information',
        quotePricer: 'Quote Provider',
        reinquiry: 'Inquire Again',
        getProductLiterature: 'Get Product Information',
        quotationTime: 'Quote Time',
        pleaseSelectPricer: 'Please select quote provider',
        notBest: 'Note: Current selection is not the best quote',
        goApp: 'Go to APP',
        serviceText: 'Application submitted, please wait patiently for processing results. For inquiries, please contact customer service: ',
        serviceText2:
            'Application submitted. SMS and email notifications will be sent when product information is available. Please check and place orders in the Star Wealth APP',
        requesting: 'Inquiring',
        requestingToast: 'Processing Inquiry',
        expired: 'Expired',
        replied: 'Replied',
        noHistory: 'No History Records',
        unableQuote: 'Unable to Quote',
        quoteing: 'Quoting',
        reinquirynotSupported: 'Re-inquiry not supported at this time',
        resubmitted: 'Inquiry Resubmitted',
        shareTitle: 'FCN Note Inquiry Share',
    },

    doingOrderMsg: 'You have {num} ongoing trade orders',
    expectedRevenue: 'Target Return',
    dynamicRetrace: 'Dynamic Drawdown',
    historyPerformance: 'Historical Performance',
    morePerformanceData: 'More Performance Data',
    moreHistoryNet: 'More Historical NAV',
    stargePerformance: 'Period Performance',
    quaterPerformance: 'Quarterly Performance',
    yearPerformance: 'Annual Performance',
    calmarRate: 'Calmar Ratio',
    sortinoRate: 'Sortino Ratio',
    investDetail: 'Investment Details',
    investStrategy: 'Investment Strategy',
    investRange: 'Investment Scope',
    quarter: 'Quarter',
    annual: 'Annual',
    year: 'Year',
    fusunProduct: 'Star Wealth Products',
    chooseMechanism: 'Selection Mechanism',
    fosunMechanism: 'Star Wealth Product Selection Mechanism',
    mechanismBrief:
        "Fosun International Securities wealth management business adopts a trinity principle of comprehensive coverage, strict selection, and timing allocation to fully absorb various investment and financing products and tools in the wealth management market, building Fosun International Securities' diverse, systematic, and comprehensive product library to achieve investors' one-stop global asset allocation needs.",
    globalCover: 'Global Coverage',
    mechanismDesc:
        'Eight investment categories + five value-added services for comprehensive coverage to achieve one-stop global asset allocation needs',
    strictChoose: 'Strict Selection',
    chooseDesc: 'Through multi-dimensional quantitative analysis, building 7P evaluation model to select outstanding star products',
    chooseSetting: 'Timing Allocation',
    chooseSettingDesc: 'Constantly monitoring macro, industry, and style timing signals to find and allocate assets with positive absolute returns',

    investScope: {
        productLine: 'Full Product Line for Primary and Secondary Investment',
        privateStock: 'Private Equity',
        structProduct: 'Structured Products',
        privateCredit: 'Private Credit',
        bondTactics: 'Bond Strategies',
        realBase: 'Real Estate & Infrastructure',
        productTactics: 'Commodity Strategies',
        stockTactics: 'Equity Strategies',
        cashManage: 'Cash Management',
        newService: 'Additional Services',
        overseasIns: 'Overseas Insurance',
        trust: 'Trust & Inheritance',
        immigrants: 'Immigration & Real Estate',
        educ: 'Education Consulting',
    },

    chooseConfig: {
        macroscopic: 'Macroeconomic',
        style: 'Style',
        financial: 'Fiscal',
        rate: 'Interest Rate',
        credit: 'Credit',
        industry: 'Industry',
        industryPolicy: 'Industry Policy',
        boom: 'Economic Prosperity',
        productionCycle: 'Capacity Cycle',
        productionRule: 'Industry Rules',
        cost: 'Value',
        growUp: 'Growth',
        marketValue: 'Market Value',
    },

    specificService: 'Dedicated Customer Service',
    productChooseMechanism: 'Product Selection Mechanism',
    privateEnjoy: 'Private Fund Exclusive',
    withUp: 'Growing Wealth Together',
    optionProduct: 'Selected Products',
    multiAsset: 'Multi-Asset',
    specificServe: 'Exclusive Service',
    selectRefer: 'Featured Recommendations',
    allProduct: 'All Products',
    yearChg: '1-Year Change',
    authView: 'Visible After Certification',
    pointRefer: 'Key Recommendations',
    productLightspot: 'Product Highlights',
    toView: 'View More',
    privateProduct: 'Private Fund Products',

    privateDisclaimer: {
        title: 'Important Information and Disclaimer',
        text1: "The content of this page is for general information and reference only. Clients shall not distribute any information in any way to others. Where the offer, solicitation, or recommendation to purchase or sell investment products would be unlawful in any jurisdiction, this service should not be considered as such offer, solicitation, or recommendation to that jurisdiction. Clients should not make investment decisions based solely on the content of this page. The funds mentioned on this page are not authorized by the SFC and are not available for public investment, and may include complex products. Before conducting any transaction, clients should take reasonable actions to ensure they clearly understand the transaction and make independent assessment of its suitability, including evaluating potential risks and benefits involved, seeking independent professional advice if needed. Clients should also carefully read and understand the fund's offering documents (including fund details and risk factors). Please note that all investments involve risks (including possible loss of principal), fund unit prices can go up and down, and past performance is not indicative of future performance.",
        text2: 'The content of this page is not and should not be construed as advice to sell, promote or solicit investment in any products. The content comes from channels that Fosun International Securities Limited considers reliable, but the company has not independently verified such information. The company makes no guarantee, warranty or representation regarding the accuracy and completeness of the information and accepts no responsibility or legal liability. Content is subject to change without notice.',
        text3: 'The content of this page has not been reviewed by the SFC.',
    },

    indicatorDeclare: {
        title: 'Indicator Explanations',
        h1: 'Annualized Return',
        text1: 'Indicates the return rate achieved over a one-year investment period.',
        h2: 'Annualized Standard Deviation',
        text2: 'An indicator showing the degree of return variation, providing a more intuitive representation of risk. Generally, a lower standard deviation is better, indicating lower risk.',
        h3: 'Maximum Drawdown',
        text3: 'Shows the maximum decline in fund value from peak to trough. Generally, a smaller absolute value is better, indicating better risk control capability.',
        h4: 'Sharpe Ratio',
        text4: 'Shows how much excess return you can expect to receive for the volatility of holding a riskier asset. Generally, a higher Sharpe ratio is better, indicating better risk-adjusted returns. It\'s an indicator measuring investment "value for money". A ratio greater than 1 means the portfolio\'s returns exceed its volatility risk; less than 1 means volatility risk exceeds returns.',
        h5: 'Calmar Ratio',
        text5: 'Shows how much excess return you can expect to receive for each unit of maximum drawdown risk. Generally, a higher ratio is better, indicating better risk-adjusted returns. Best used for comparing similar funds.',
    },

    orderDetailFields: {
        confirmInfo: 'Confirmation Information',
        orderInfo: 'Order Information',
        applySuccess: 'Application Successful',
        applySuccessTips: 'We will freeze your account funds when processing the order. Please ensure sufficient funds in your account before then',
        buyMore: 'Buy More',
        orderRecord: 'Order Records',
        months: '{num} Months',
        applySuccessTipsForBond: 'Your account assets will be frozen upon order submission. Please wait patiently for order execution',
        tradeSuccessRemind: 'Trade success is subject to fund company confirmation',
        applySuccessTipsForBill: 'Your account assets will be frozen upon order submission. Please wait patiently for order execution',
    },

    orderDetailCols: {
        filledGrossAmount: 'Confirmed Amount',
        filledPrice: 'Confirmation Price',
        filledFeeAmount: 'Estimated Fees',
        settleDate: 'Confirmation Time',
        bondProductName: 'Bond Name',
        currency: 'Currency',
        applyGrossAmount: 'Order Amount',
        orderDirection: 'Order Type',
        orderStatus: 'Order Status',
        orderNumber: 'Order Number',
        submitTime: 'Order Time',
        orderSource: 'Order Source',
        orderWay: 'Order Method',
        billsProductName: 'Note Name',
        productPeriod: 'Maturity Date',
        productYield: 'Annualized Rate',
        parCash: 'Face Value',
        accruedInterest: 'Accrued Interest',
        buyPrice: 'Purchase Price',
        sellPrice: 'Selling Price',
        bondQuanityTip:
            'Confirmed bond purchase orders may have delayed display in [My Holdings], expected to be synchronized on the next Hong Kong trading day after confirmation',
        cashOrderDesc: 'Note: Due to changes in product NAV, actual amounts are subject to trade execution',
    },

    // Bond Related
    whatIsBond: 'What is Bond Investment?',
    toSee: 'View Details',
    expireIncome: 'Yield to Maturity',
    residueDate: 'Days Remaining',
    bondLevel: 'Bond Rating',
    closingPrice: 'Reference Price',
    couponRate: 'Coupon Rate',
    maturityDate: 'Maturity Date',
    dividendFrq: 'Coupon Frequency',
    baseBrief: 'Basic Overview',
    companyBrief: 'Issuer Profile',
    priority: 'Priority',
    bondMold: 'Bond Type',
    bondCategory: 'Bond Category',
    tradeCurrency: 'Trading Currency',
    publishDate: 'Issue Date',
    offeringSize: 'Issue Size',
    minInitialCash: 'Minimum Purchase Amount',
    creditEntity: 'Credit Entity (Short Name)',
    creditEntityFull: 'Credit Entity (Full Name)',
    publisher: 'Issuer',
    mainBusiness: 'Main Business',
    businessAddr: 'Business Address',
    historyTrend: 'Historical Trend',
    historyPrice: 'Historical Quotes',
    unitAmount: 'Unit Amount',
    interest: 'Interest Collection Fee',
    moreHistoryPrice: 'More Historical Quotes',
    costEstimate: 'Cost Estimate',
    extraFeeAmount: 'Accrued Interest (365-day basis)',
    allCostEstimate: 'Total Estimate',
    interestEstimate: 'Accrued Interest Estimate',
    costTip: 'Special Note: The estimated accrued interest here may differ from actual value, subject to final trade confirmation',
    accountHave: 'Available Balance',
    andNeed: 'Additional Required',
    buyAllCost: 'Estimated Payable Amount',
    parMustMulti: 'Face value must be in multiples of {num}',
    buyPrice: 'Purchase Price',
    referPrice: 'Reference Bid',
    referSellPrice: 'Reference Ask',
    buyAmount: 'Purchase Amount',
    minInitialTips: 'Minimum face value starts from {num}',
    saveCapital: 'Deposit Funds',
    bondDetail: 'Bond Details',
    buyBond: 'Buy Bond',
    dollarBond: 'USD Bond Section',
    submitResult: 'Submission Result',
    verifyToUnlock: '*Complete professional investor certification to view',
    decreaseUnit: '<span>Increases in units of <span class="{classname}">{num}</span>{currency}</span>',
    parFaceCash: 'Face Value',
    accruedInterest: 'Estimated Accrued Interest',
    pbDataOrigin: 'Data Source: Bloomberg',
    day7Annual: '7-Day Annualized Yield',
    wfIncome: 'Daily Income per 10,000',
    hisDay7Annual: 'Historical 7-Day Annualized Yield',
    dayTrip: 'Daily Change',
    nearlyWeek: '1 Week',
    top10holdings: 'Top Holdings Ratio',
    inActiveMsg: 'Sorry, the product you are viewing has been delisted',
    suspensionMsg: 'This product is currently suspended for subscription',
    note: 'Note',

    piGuide: {
        warmTip: 'Important Notice',
        eightMillionTip:
            'You have not been certified as a professional investor. According to regulatory requirements, you need to provide proof of HKD 8 million in assets. Please upload asset proof or deposit sufficient funds',
        calcMaybeDelay: 'Calculation may be delayed, please refer to your actual assets',
        uploadAssetFile: 'Upload Proof',
        depositNow: 'Deposit Now',
        invitationAuthenticate: 'Dear client, you meet the professional investor requirements. You are now invited to complete certification',
        authenticateNow: 'Certify Now',
        cancel: 'Cancel',
        viewApplyProcessingTip:
            'Dear client, you have submitted the professional investor certification application. Click the button below to check application progress',
        viewApplyProcessing: 'Check Progress',
        zhybdj: 'Account Frozen',
    },

    piAuthenticate: 'Professional Investor',
    jqrnh: '7-Day Annualized',
    jqrnhIncome: '7-Day Annualized Return',
    xxlc: 'Star Selection',
    mr: 'Buy',
    jhlc: 'Balanced Investment',

    // Fund Selection by Stock
    fundSelectionByStock: {
        title: 'Fund Selection by Stock',
        searchPlaceholder: 'Search Funds by Stock',
        searchPlaceholder2: 'Enter Code/Name',
        searchPlaceholder3: 'Enter Stock Code/Name',
        fundHot: 'Popular Stocks in Funds',
        searchHot: 'Popular Searches',
        searchHistory: 'Search History',
        deleteTips: 'Confirm delete all history?',
        affiliatedFund: 'Associated Funds',
        zjjzc: 'Fund Major Holdings',
        jsnzf: '3-Year Change',
        cczb: 'Holding Ratio',
        sxjj: 'Filter Funds',
        jsqbh: 'Change from Last Period',
        zhpf: 'Comprehensive Rating',
        updateDate: 'Update Date',
        totalFund: 'Total {num}',
        fundRatioTips: 'Note: Fund holdings are not real-time data, for reference only',
        containAllStock: 'Contains All Stocks',
        containPartStock: 'Contains Some Stocks',
        chosenStock: 'Selected Stocks',
        addStock: 'Add Stock',
        addFund: 'Add Fund',
        stockName: 'Stock Name',
    },

    allServices: 'All Services',
    tools: 'Tools',
    fundComparison: 'Fund Comparison',

    // Fund Comparison
    compare: {
        compare: 'Compare',
        fundCompare: 'Fund Comparison',
        hadSelect: '{num} Selected',
        selectLimit: 'Maximum 4 funds',
        startCompare: 'Start Comparison',
        track: 'History',
        self: 'Watchlist',
        holding: 'Holdings',
        same: 'Same Category',
        wrongTips: 'Note: You have selected different fund types. Comparing funds of the same type is recommended for better reference',
        noSelectFund: 'No fund selected',
        selectFund: 'Select Fund',
    },

    // Radar Chart
    radar: {
        comprehensivePerformance: 'Comprehensive Performance',
        comprehensiveScore: 'Comprehensive Score',
        yield: 'Return Performance',
        upCapture: 'Upside Capture',
        maxDrawown: 'Drawdown Management',
        stdDev: 'Volatility Management',
        downCapture: 'Downside Capture',
        battingAvg: 'Market Outperformance',
        analysisDetail: 'Analysis Details',
        viewDetail: 'View Details',
        dimension: 'Dimension',
        ranking: 'Category Ranking',
        maxFund: 'Maximum {num} funds',
        riseFall: 'Return',
        upCaptureRate: 'Upside Capture Ratio',
        maxDrawownRate: 'Maximum Drawdown',
        stdDevRate: 'Annualized Standard Deviation',
        downCaptureRate: 'Downside Capture Ratio',
        similarFund: 'Similar Funds',
        nearThreeYearRiseFall: '3-Year Return',
        greatThanAverage: 'Outperforms {percent} of peer funds',
        score: 'Score',
        startAmount: 'Min. Investment',
        fundComprehensivePerformance: 'Fund Comprehensive Performance',
    },

    fundText1:
        'Part of the tools, materials and data on this page are provided by Morningstar (Asia) Limited ("Morningstar"), or Fosun International Securities Limited ("Fosun International Securities") uses tools made from materials provided by Morningstar for analysis purposes. However, the content of this page is for reference only and does not constitute any investment advice. In addition, Fosun International Securities makes no guarantee as to the completeness, accuracy and timeliness of the information contained herein. Please verify all information before use and do not make any investment decisions before consulting professional investment advisors.',
    fundText2: 'Category Ranking',
    fundText3: 'Annualized Dividend Yield',
    fundText4: '10-Year Annualized Return',
    fundText5: 'Years Since Inception',
    fundText6: 'Select funds with highest dividend yield.',
    fundText7: 'Well-established funds with over 10 years history and average annual return above 8% over the past 10 years.',
    fundText8: 'Funds with high dividend yield and stable performance.',
    fundText9: 'Funds with high dividend yield and stable performance.',
    fundText10: 'Funds with high dividend yield and stable performance.',
    fundText11: 'Funds with high dividend yield and stable performance.',
    fundText12:
        'Recommendations based on analysis of your watchlist, risk assessment and browsing preferences. These recommendations are for reference only in your investment product selection process and do not constitute investment advice.',
    fundText13:
        'Compare funds across six dimensions including "Market Outperformance", "Return Performance", "Volatility Management", "Upside Capture", "Downside Defense" and "Drawdown Management", supplemented by Morningstar ratings and recent market trends analysis, to screen out funds with good performance and future potential.',
    fundText14: 'Returns over 1-year, 3-year and 5-year periods all outperform peer funds;',
    fundText15: '3-year and 5-year Morningstar ratings are 4 stars or above.',
    fundText16: 'Fund Rankings',
    fundText17: 'Cash Management',
    fundText18: 'Holding Your Focus',
    fundText19: 'Research Reports',
    fundText20: 'No Reports Available',
    fundText21: 'High Risk-Adjusted Return Ranking',
    fundText22: 'Dividend Fund Ranking',
    fundText23: 'Leading Dividend Yield',
    fundText24: 'Outstanding Veteran Fund Ranking',
    fundText25: 'Over 10 years history, over 10x return',
    fundText26: 'Leading returns, outperforming peers',
    fundText27: 'Performance Excellence Ranking',
    fundText28: 'High Investment Value',
    fundText29: 'Cash Manager, Auto Subscription/Redemption',
    ruleDescript:
        'Note: Fund management fees, custody fees and other expenses are deducted daily from fund assets. Fee data shown on the page comes from third parties and may differ from actual fund company rates. For reference only, please refer to offering documents for specifics.',
    ji: 'and',
    allAccount: 'All Accounts',
    chooseAsset: 'Select Asset',
    cashAccount: 'Cash Account',
    marginAccount: 'Margin Account',
    starBanner: {
        pay: 'Fee',
        openStar: 'Open Star Wealth',
        profit: 'Returns exceed savings accounts, earnings calculated from purchase date',
        open: 'Open Now',
    },
    intentionalPrice: 'Target Price',
    ygAmount: 'Estimated Transaction Amount',
    ygjfAmount: 'Estimated Payment Amount',
    conOfInvestment: 'Investment Concentration',
    typeOfInvestor: 'Investor Type',
    jzdtips: 'Your selected investment concentration limit does not match this product',
    readContent: 'Please read the following agreement carefully',
    cancelUpgrade: 'Cancel Upgrade',
    publicRisk: 'Risk Disclosure/Disclaimer',
    transactionAmount: 'Transaction Amount',
    zdkmc: 'Maximum Sellable Amount',
    tzhsxpp: 'Investment Suitability Match',
    stocksHKD: 'Hong Kong Stocks',
    stocksUSD: 'US Stocks',
    stocksCNH: 'A-Share Connect',
    specialty: 'Professional',
    ordinary: 'Regular',
    checkTheAgreement: 'View Agreement',
    shortBondComment: 'Achieve short-term income growth with flexible withdrawals',
    longBondComment: 'Investment safe haven for stable cash value growth',
    follow: {
        title: 'Wealth Management',
        investmentMigrate: 'Investment Immigration Portfolio Section',
        combinationName: 'Portfolio Name',
        orderSource: 'Order Source',
        positionDistribution: 'Portfolio Position',
        rebalancingRecords: 'Rebalancing Records',
        explain: 'Explanation',
        rebalancingRecordsExplain:
            'Reference transaction prices for initial/rebalancing positions use unadjusted prices; portfolio return calculations use forward-adjusted prices.',
        rebalancingZeroHint: 'Stocks with 0% position will be removed, rebalancing direction is [Sell], please confirm this rebalancing operation',
        orderCashExchangeHint:
            'Order amount exceeds current currency cash, {amountTip} will use other currencies as buying power. Interest will accrue if not exchanged promptly',
        orderMarginFeeHint: 'Order amount exceeds cash buying power, {amountTip} will use margin financing and incur interest charges',
        with: 'and',
        holdDayNum: 'Holding Period (Days)',
        holdRatio: 'Holding Ratio',
        limitedPrice: `Limit Buy <span class="c-theme">&nbsp;{num}&nbsp;</span> Units`,
        fundPrice: `Buy <span class="c-theme">&nbsp;{num}&nbsp;</span> Units`,
        portfolioOrderDisclaimer: 'Portfolio Order Disclaimer',
        noMore: 'No More Data',
        fundName: 'Fund',
        stockName: 'Stock',
        mix: 'Mixed',
        investmentConcentration: 'Investment Concentration',
        orderTitle: 'Portfolio Order',
        orderResultTitle: 'Order Result',
        ruleTitle: 'Related Agreements and Documents',
        combinationTitle: 'Easy Investment Service',
        findCombinationTitle: 'Discover Investment Portfolios',
        combinationRecordDetailTitle: 'Portfolio Order Details',
        combinationRecordTitle: 'Portfolio Order Records',
        detailTitle: 'Portfolio Product Details',
        distributeTitle: 'Position Details',
        distributeRecordsTitle: 'Rebalancing Records',
        noDataText: 'No Data Available',
        openCat: 'Register to View',
        advantageInvest: 'Selected Investment Strategies',
        openText: 'Register Now',
        foundDayNum: 'Portfolio Age: {foundDayNum} Days',
        accountIncome: 'Total Returns',
        dayRise: 'Daily Change',
        brief: 'Strategy Analysis:',
        quitBuy: 'One-Click Buy',
        followTitle: 'Investment Following',
        performanceTitle: 'Portfolio Return Trend',
        hkStock: 'HK Stocks',
        usStock: 'US Stocks',
        bondHKD: 'HKD Bonds',
        bondUSD: 'USD Bonds',
        fundStock: 'Equity Fund',
        fundBond: 'Bond Fund',
        fundMixed: 'Mixed Fund',
        fundCurrency: 'Money Market Fund',
        delayText: 'As required by the exchange, current status shows 15-minute delayed quotes',
        HKDelayText: 'As required by the exchange, current status shows 15-minute delayed HK stock quotes',
        USDelayText: 'As required by the exchange, current status shows 15-minute delayed US stock quotes',
        recommondPrice: 'Reference Transaction Price:',
        recommondPureNumber: 'Reference NAV:',
        rebalanceText: 'Total {total} Rebalances',
        nameCode: 'Name Code',
        stockCode: 'Stock Code',
        price: 'Price',
        directionStatus: 'Direction/Status',
        quantityAmount: 'Units/Amount',
        quantityPrice: 'Quantity/Price',
        waitText: 'Pending Execution',
        pending: 'Pending',
        canceled: 'Canceled',
        successText: 'Executed',
        partSuccess: 'Partially Executed',
        partCancel: 'Partially Canceled',
        unfold: 'Expand',
        fold: 'Collapse',
        orderCount: 'Portfolio Order Records ({total})',
        exampleRate: 'Investment Concentration Assessment: Planned investment amount as a proportion of your assets',
        matchText: 'Purpose: Evaluate if your investment concentration matches product risk',
        productRate: 'This product supports an investment concentration ratio of {investFocusDegree}',
        orderType: 'Order Type',
        descriptAmount: 'Estimated Purchase Amount',
        accouontUse: 'Account Available',
        maxQty: 'Maximum Buying Power',
        holdRate: 'Holding Ratio',
        agreeText: 'I agree to purchase this fund portfolio at the set investment ratio',
        confirmBuy: 'Confirm Purchase',
        limitOrder1: 'Enhanced Limit Order',
        limitOrder2: 'Limit Order',
        lastNumber: 'Please select at least one fund',
        fundAmount: 'Fund Quantity',
        stockAmount: 'Stock Quantity',
        alreadySubmit: 'Order Submitted',
        errorReason: 'Order failed, your set investment ratio does not meet requirements, please adjust and resubmit',
        adjustmentText: 'Adjust Now',
        minInitialAmountText: 'Minimum initial investment amount: {minInitial}{currencyName}',
        heightPrice: '{percent}% above current price',
        lowPrice: '{percent}% below current price',
        tradeMarket: 'Trading Market',
        orderResultText: 'Purchased {buyProductNum} {stockText}, please wait patiently for order execution',
        orderInfo: 'Portfolio Order Information',
        fundDetail: 'Fund Order Details',
        stockDetail: 'Stock Order Details',
        orderRecord: 'Investment Order Records',
        holdRecord: 'Position Order Records',
        reviewOrderRecord: 'View Order Records',
        stockHkName: 'HK Stocks',
        stockUsName: 'US Stocks',
        pubFundName: 'Public Funds',
        combinationDecript: 'Portfolio Order Disclaimer',
        selfIncome: 'Portfolio Return',
        lessOneYear: 'Less than 1 year',
        oneToFiveYear: '1-5 years',
        sixToTenYear: '6-10 years',
        moreTenYear: 'Over 10 years',
        riskStatement: 'Portfolio Product Disclaimer',
        calcTipTitle: 'The system will calculate the closest share quantity to match your portfolio allocation based on your input amount.',
        calcTipForInputAmount: 'Input Amount',
        calcTipForSystemAmount: 'System Calculated Amount',
        calcTipForBestAmount: 'Optimal Portfolio Amount',
        calcTipForStockCount: 'Stock Purchase Quantity',
        calcTipForFundCount: 'Fund Purchase Quantity',
        calcTipForUnvalidAmount:
            'Your input amount is less than the minimum purchasable shares for this portfolio, please re-enter the purchase amount.',
        followTradeDescriptionTitle: 'Fund Portfolio Trading Instructions',
        tradeAmountDescTitle: 'Transaction Amount Description',
        tradeAmountDescContent: "Account available balance = Payment account's withdrawable cash balance",
        tradeAccountTip: 'Fund portfolio trading rules follow individual fund trading rules, see trading rules for each fund in the portfolio',
        amountCurrency: 'Amount/Currency',
        amount: 'Amount',
        cancelFail: 'Cancel/Failed',
        cancelEnding: 'Cancel/Terminated',
        estimateBuy: 'Estimated Purchase',
        actuallyBuy: 'Actual Transaction',
        heightenLimitOrder: 'Enhanced Limit Order',
        emptyLotNumTip: 'Please modify stock quantity',
        portfolioStopTip: 'This portfolio has been discontinued',
        fansNum: 'Followers',
        personalPage: 'Personal Page',
        dayProfit: 'Daily Profit',
        portfolioComment: 'Portfolio Comments',
        top: 'Pin',
        topSuccess: 'Successfully Pinned',
        confirmDeleteMessage: 'Confirm deletion of this portfolio comment?',
        deleted: 'Deleted',
        newest: 'Latest',
        orderType1: 'At-auction Limit Order',
        orderType2: 'At-auction Order',
        orderType3: 'Limit Order',
        orderType4: 'Enhanced Limit Order',
        orderType5: 'Special Limit Order',
        orderType6: 'Pre-IPO Order',
        orderType7: 'Market Order',
        orderType8: 'Odd Lot Order',
        orderType31: 'Conditional Order - Trailing Stop',
        orderType32: 'Conditional Order - Take Profit Limit',
        orderType33: 'Conditional Order - Trailing Stop',
        rebalance: 'Rebalance',
        simulateCalculations: 'Simulate Calculations',
        followPortfolio: 'Follow Portfolio',
        unfollowPortfolio: 'Unfollow Portfolio',
        advisory: 'Advisory',
        manager: 'Manage',
        comment: 'Comment',
        modifyingPortfolioInfo: 'Modify Portfolio Information',
        stopPortfolio: 'Discontinue Portfolio',
        trade: 'Trade',
        createCommentPage: 'Post Portfolio Comment',
        createCommentplaceholder: 'Please enter your portfolio comment content',
        confirmCreate: 'Confirm Post',
        createSuccess: 'Posted Successfully',
        openAaccountFirst: 'Please complete securities account opening first',
        selectedList: 'Selected List',
        cannotDelete: 'This product has set position ratios, please delete the product first',
        userName: 'Username',
        oneAccOneWorld: 'One Account, Global Investment',
        loginRegister: 'Login/Register',
        riskTip:
            '1. These investment portfolios are simulated portfolios created by users on Star Wealth, distinct from actual trading behavior, and do not constitute investment advice. Users bear their own risks for trading based on these.\n2. Simulated investment portfolios are free features provided by Star Wealth to help users record their investment strategies. Users can also make their created portfolios public or share them for investment communication purposes.\n3. Star Wealth does not charge any fees for simulated investment portfolios and firmly opposes and combats illegal paid stock recommendation scams.\n4. Simulated investment portfolio data is for reference only. While Star Wealth strives for timeliness and accuracy of data, limitations due to data transmission delays, data source or processing errors, and other potential issues mean Star Wealth cannot guarantee complete timeliness and accuracy.\n5. Markets involve risks, invest prudently.',
        realOrder: 'Live Trading Purchase',
        realOrderTag: 'Real Trading',
        realOrderConfirmTitle: 'Do you want to place a real buy order based on the simulation calculator results?',
        realOrderFreezeAmount: 'Actual Deduction Amount',
        totalPurchaseCount: `Total purchase of <span class='summary-count__value'>{count}</span> {marketName}`,
        resetToBestAmountTip: 'Your input amount cannot buy all positions at optimal ratios, automatically reset to optimal portfolio amount.',
        overLimitsError: `Exceeded {count} characters, please modify`,
        followSearchHint: `Please enter portfolio name`,
        shareFollowDetailDesc: 'Easy Investment Service - Selected Brand Portfolios from the Market',
        searchHistory: 'Search History',
        upgradeInvestment: 'Upgrade Investment Advisory',
        investmentAssets: 'Advisory Assets',
        notEnoughCashTip: 'Insufficient funds, cannot submit application',
        piVisible: 'PI Certification Required',
    },
    investAdvisory: {
        assets: 'Advisory Assets',
        profitLoss: 'Profit/Loss Details',
        holdDetail: 'Position Details',
        tradeDirection: 'Rebalancing Direction',
        additionalBuy: 'Additional Purchase',
        soldOut: 'Full Liquidation',
        portfolioTransfer: 'Portfolio Rebalancing',
        placeholder: 'Please enter amount',
        confirmBuy: 'Confirm Purchase',
        confirmSell: 'Confirm Sale',
        unbuild: 'Not Initiated',
        builded: 'Initiated',
        systemTransfer: 'System Rebalancing',
        myInvestGroup: 'My Investment Portfolio',
        portfolioRebalancing: 'Portfolio Rebalancing',
        positionDetails: 'Position Details',
        orderRecord: 'Order Records',
        incomeDetail: 'Income Details',
        applyStatus: 'Application Status',
        applyAmount: 'Application Amount',
        rejected: 'Rejected',
        shenhezhong: 'Under Review',
        orderRecords: 'Advisory Portfolio Order Records',
        noInvestList: 'No Advisory Portfolios',
        accumulateProfitLoss: 'Accumulated P/L',
        totalNumberAndTime: 'Total {count} products, updated to {date}',
        accumulateProfit: 'Accumulated Profit',
        accumulateLoss: 'Accumulated Loss',
        monthProfit: '{month} Monthly Return',
        yearProfit: '{year} Annual Return',
        profitCanlendar: 'Return Calendar',
        currentMonthProfit: 'Current Month Return',
        currentDayProfit: 'Current Day Return',
        selectMonth: 'Select Month',
        selectYear: 'Select Year',
        todayPL: "Today's P/L",
        szsl: 'Market Value/Quantity',
        priceCosting: 'Current Price/Cost',
        holdingPL: 'Position P/L',
        unrealizedPL: 'Unrealized P/L',
        realizedPL: 'Realized P/L',
        clickMoreInfo: 'Click to show more options',
        monthIndex: 'Month {month}',
        placeInMiddle: 'Middle Office Order',
        pleaseContactService: 'Please contact customer service for inquiry',
        firstTransferAmount: 'Initial Transfer Amount',
        estimatedClearance: 'Estimated Total Liquidation',
        noHoldSell: 'No positions to sell',
        clearHolding: 'Client Liquidation',
    },
    closePortfolio: {
        confirmClose: 'Confirm portfolio discontinuation?',
        inputCloseReason: 'Please enter discontinuation reason, which will be shown to clients. Please fill in carefully',
        closeDescribe:
            'After discontinuing the portfolio:\n1. Return rate calculation will stop\n2. Cannot perform rebalancing, modification, or order operations\n3. Cannot reactivate the portfolio',
        reasonEmptyError: 'Please enter discontinuation reason',
        reason_certain: 'Discontinuation reason contains sensitive words, please re-enter',
        closeSuccess: 'Portfolio discontinued successfully',
        closeError: 'Portfolio discontinuation failed, please try again',
    },
    editPortfolioInfo: {
        page: 'Edit Information',
        namePlaceholder: 'Portfolio name limited to 10 characters',
        briefPlaceholder:
            'Please enter your investment strategy and recommendations for this portfolio. Good investment strategies attract more followers',
        briefPlaceholder2: 'Please enter your investment strategy and recommendations~',
        title: 'Modify Portfolio Information',
        success: 'Modified Successfully',
        nameOneWord: 'Portfolio name must be at least 1 character',
        brief: 'Investment Strategy Analysis',
        briefEmpty: 'Investment strategy analysis cannot be empty',
        confirmEdit: 'Confirm Modification',
        name_certain: 'Portfolio name contains sensitive words, please re-enter',
        brief_certain: 'Investment strategy analysis contains sensitive words, please re-enter',
        confirmGoBack: 'Confirm abandoning current edits?',
    },
    createComment: {
        error1: 'Portfolio comment cannot be empty',
        error2: 'Portfolio comment must be at least 2 characters',
        error3: 'Portfolio comment contains sensitive words, please re-enter',
    },
    rebalancing: {
        page: 'Rebalancing',
        abandon: 'Confirm abandoning this rebalancing?',
        delete: 'Confirm deleting this product?',
        success: 'Rebalancing successful',
        addStock: 'Add Stock',
        addFund: 'Add Fund',
        minimumError: 'Please keep/add at least one product',
        selectRatio: 'Select Rebalancing Ratio',
        noCash: 'Cash ratio exhausted, please adjust positions',
        plsSetRatio: 'Please set position ratio',
        changedRatioError: 'Current position ratios have changed, please re-enter rebalancing page',
        rebalancingFailed: 'Rebalancing failed, please try again',
    },
    simulation: {
        page: 'Simulation Calculator',
        trade: 'Simulated Trading',
        estimatedAmount: 'Estimated Purchase Amount',
        disclaimer0: 'Disclaimer',
        disclaimer1:
            '1. These investment portfolios are simulated portfolios created by users on Star Wealth, distinct from actual trading behavior, and do not constitute investment advice. Users bear their own risks for trading based on these.',
        disclaimer2:
            '2. Simulated investment portfolios are free features provided by Star Wealth to help users record their investment strategies. Users can also make their created portfolios public or share them for investment communication purposes.',
        disclaimer3:
            '3. Star Wealth does not charge any fees for simulated investment portfolios and firmly opposes and combats illegal paid stock recommendations. Users should be cautious of illegal paid stock recommendation scams.',
        disclaimer4:
            '4. Simulated investment portfolio data is for reference only. Past performance does not reflect future performance. While Star Wealth strives for timeliness and accuracy of data, limitations due to data transmission delays, data source or processing errors, and other potential issues mean Star Wealth cannot guarantee complete timeliness and accuracy.',
        disclaimer5: '5. Markets involve risks, invest prudently.',
        buyIn: 'Live Trading Purchase',
        totalPurchaseCount: `Total purchase of <span class="bold highlight"> {num} </span> {type} (Enhanced Limit Order)`,
        totalPurchaseCountUS: `Total purchase of <span class="bold highlight"> {num} </span> {type} (Limit Order)`,
        totalFundPurchaseCount: `Total purchase of <span class="bold highlight"> {num} </span> funds`,
    },
    master: {
        masterTitle: 'Star Select Investment Zone',
        investmentExp: 'Investment Experience',
        fans: 'Followers',
        follow: 'Follow',
        investmentPhilosophy: 'Investment Philosophy:',
        racetrack: 'Expertise Areas:',
        lessOneYear: 'Less than 1 year',
        oneToFiveYear: '1-5 years',
        sixToTenYear: '6-10 years',
        moreTenYear: 'Over 10 years',
        nearOneWeekProfit: '1-Week Return',
        nearOneMonthProfit: '1-Month Return',
        nearThreeMonthProfit: '3-Month Return',
        nearSixMonthProfit: '6-Month Return',
        nearOneYearProfit: '1-Year Return',
        nearThreeYearProfit: '3-Year Return',
    },
    starSel: {
        starSelTitle: 'Star Select Arena',
        w1Profit: 'Weekly Return',
        m1Profit: 'Monthly Return',
        m3Profit: 'Quarterly Return',
        y1Profit: 'Annual Return',
        follower: 'Followers',
    },
    followOrder: {
        selectNum: 'Select Units',
        inputAmount: 'Enter Amount',
        selectOrderTypeTitle: 'Select Portfolio Order Type',
        confirm: 'Confirm',
        selectBuyNum: 'Select Purchase Units',
        cannotSelect: 'Current maximum buying power insufficient, following tiers unavailable for purchase',
        per: 'Unit',
    },
    customDate: 'Custom Date',
    customOrder: 'Client Order',
    systemOrder: 'System Order',
    worthTrend: 'NAV Trend',
    investExpression: 'Investment Overall Performance',
    investExpressionDetail: 'Investment Performance Details',
    preMoreThanInvest: 'Overall performance surpasses',
    sufMoreThanInvest: 'of investors',
    dimension: 'Dimension',
    platformInvestor: 'Platform Investors',
    preMonth: 'Last Month',
    openToDay: 'Since Account Opening',
    detailText: 'Details',
    bondExpiredTip: 'This bond product has matured, buying/selling not supported',
    bondDisabledTip: 'This bond product has been delisted, buying not supported',
    perpetual: 'Perpetual',
    adjustAutoManage: 'Idle Funds Auto Management',
    reckonInPower: 'Included in securities buying power, can directly buy stocks and IPO',
    followNoobGuide: 'Professional fund managers help you invest worry-free',
    day: 'Day',
    riskRemark: '*Note: 1-year annualized return equals past 1-year cumulative return',
    noAnnualProfit: 'No annual return available',
    bondRedeemLowerLeast: 'Face value below 200,000 {currency}, order may not be executed',
    wealthProfessor: 'Idle Money Investment Expert',
    openEcashService: 'Open Star Cash Service',
    ecashOpenDialog: {
        suggestTransform: 'Detected you have opened Star Cash service, suggesting the following actions:',
        suggest1: '1. Sell currently held public money market funds today;',
        suggest2: '2. System will automatically buy Star Cash money market fund product with highest 7-day annualized return tomorrow;',
        tradeScene: 'Star Cash Money Market Fund Trading Scenarios',
        stockTrade: 'Stock Trading',
        repay: 'Account Repayment',
        IPO: 'IPO Subscription',
        openSlogan1: 'Star Cash Money Market Fund (Included in Securities Buying Power)',
        openSlogan2: 'Flexible use of idle funds, balance trading and investment',
        openSuggest: 'After opening, note the following:',
    },
    nextTalk: 'Talk Later',
    sellNotEnoughTips: 'Insufficient sellable amount',
    ecashOpenRemindTitle: 'Star Cash Money Market Fund Purchase Notice',
    ecashOpenRemindMessage:
        'The fund you are purchasing is a "Star Cash" money market fund. After successful purchase, it will automatically increase your securities account buying power. The system will automatically enable "Star Cash" auto-redemption service (automatically redeem Star Cash to pay account debt). Star Cash money market fund assets purchased and confirmed today will be automatically included in securities account buying power at 06:00 tomorrow. For "Star Cash" service details, click to learn more',
    autoExchange: 'Auto Currency Exchange',
    autoExchangeDesc: 'For cross-currency transactions, you can choose to enable auto currency exchange or manually exchange currencies',
    toOpenAutoExchange: 'Enable Auto Currency Exchange',
    isUsePurchasingPowerMargin:
        'Order amount exceeds cash buying power, <span class="important">{amount} {currency}</span> will use margin financing and incur interest charges',
    isUsePurchasingPowerCash:
        'Order amount exceeds current currency cash, <span class="important">{amount} {currency}</span> will use other currencies as buying power. Interest will accrue if not exchanged promptly',
    willUseMargin: 'Purchase will use margin amount',
    billRiskRemind: `Note:\n1. For bills with terms over 12 months and other terms, please contact your dedicated client manager;\n2. Above product information and agreement documents are for reference only, product terms subject to final order transaction, clicking buy only represents booking client manager to provide latest information;\n3. Bill maturity payment usually takes {day}, final timing subject to custodian bank's actual transfer time;`,
    estimateIntoFormula: 'Estimated receipt amount = Sold units * Latest NAV - Estimated selling fees',
    estimateIntoReference:
        "Estimated receipt amount calculated using latest NAV ({nav}/unit) for reference only, actual receipt amount subject to fund company's final confirmation.",
    estimateIntoStand: '(Estimated based on latest NAV, subject to actual receipt amount)',
    orderRejectReason: 'Order termination reason:',
    pleaseInputTZJZD: 'Please select product investment concentration',
    pleaseInputXGXY: 'Please check and agree to related agreements',
    cantEmptyForPrice: 'Price cannot be empty',
    cantBeZeroForPrice: 'Price cannot be zero',
    cantEmptyForAmount: 'Face value cannot be empty',
    greatThanCashTip: 'Exceeds available cash, please deposit funds',
    greatThanPurchasingPowerTip: 'Insufficient maximum buying power, please increase',
    tradeRemind: 'Trading Reminder',
    billNoTradeTime: 'Not during bill product trading hours, trading expected to open next Monday 21:00',
    billNoTradeTimeHtml:
        '<p>Not during bill product trading hours, trading expected to open <span style="color: #FF6907;">next Monday 21:00</span></p>',
    PIuploadText: 'Submit',
    PIupdateText: 'Modify',
    PIDialogPersonText:
        'Dear client, your professional investor asset proof has expired. To ensure your investment activities are not affected, please submit updated asset proof before {date}, thank you!',
    PIDialogComText:
        "Dear client, your company's professional investor asset proof has expired. To ensure your company's investment activities are not affected, please submit updated asset proof before {date}, thank you!",
    PITooltipPersonText: 'Your professional investor asset proof has expired, please submit updated asset proof before {date}, thank you!',
    PITooltipComText: "Your company's professional investor asset proof has expired, please submit updated asset proof before {date}, thank you!",
    PIReTooltipPersonText: 'Your professional investor asset proof submission was not approved, please resubmit asset proof before {date}',
    PIReTooltipComText: "Your company's professional investor asset proof submission was not approved, please resubmit asset proof before {date}",
    goCmhkAssetBtn: 'Go to Star Wealth',
    addWealthCounselor: 'Add Wealth Advisor',
    fixed: {
        fixedDeposit: 'Fixed Deposit',
        annualInterestRateAft: 'Expected Annual Interest Rate (After Fees)',
        repaymentOrderText: 'You have <span class="msg-number"> {repaymentLength} </span> matured fixed deposit transactions pending repayment',
        startInterest: 'Interest Start Date',
        subStarts: 'Subsequent Investment Start',
        subEnd: 'Subsequent Investment End',
        minimumPurchase: 'Minimum Deposit',
    },
    starSpecialAccountScope: {
        repaymentOrderText:
            'You have <span class="msg-number"> {repaymentLength} </span> Star Wealth special account service transactions due for repayment',
    },
    stopSellingBtn: 'Suspend Sales',
    onlySellForProduct: 'This product has suspended sales, only sell orders supported',
    stopTrade: 'This product currently does not support trading',
    attention: {
        title: 'Following and Fans',
        myFans: 'Fans',
        myAttention: 'Following',
        defaultBrief: 'No personal introduction yet~',
        takedownName: 'This user has been deactivated',
        customOutageBrief: "This user's Easy Investment service has been suspended",
    },
    customerDetail: {
        title: 'Personal Homepage',
        investExp: 'Investment Experience',
        year: 'Year',
        tenYearMore: 'Over 10 Years',
        follow: 'Follow',
        followed: 'Following',
        unFollow: 'Unfollow',
        unFollowed: 'Unfollowed',
        editInfo: 'Edit Profile',
        fans: 'Fans',
        more: 'More',
        portfolio: 'Investment Portfolio',
        active: 'Active',
        close: 'Discontinued',
        createdPortfolio: 'Created',
        followPortfolio: 'Following',
        toCreatePortfolio: 'Create Portfolio',
        myPortfolio: 'My Portfolio',
        profolioRecord: 'Portfolio Order Records',
        realOrderRecond: 'Live Trading Records',
        myInvestAsset: 'My Advisory Assets',
        all: 'All',
        hk: 'Hong Kong Stocks',
        us: 'US Stocks',
        mixture: 'Mixed',
        fund: 'Fund',
        followNum: 'Followers',
        createDays: 'Portfolio Age (Days)',
        calRev: 'Cumulative Return',
        weekRev: '1-Week Return',
        noData: 'No Portfolios',
        gotoDiscover: 'Discover Portfolios',
        personalIntroduce: 'Personal Introduction',
        introduceTip: 'Please enter your personal introduction',
    },
    createPortfolio: {
        title: 'Create Portfolio',
        selMarket: 'Select Market',
        addPortfolio: 'Add Product',
        finishCreate: 'Complete Creation',
        stockTitle: 'Stock Market',
        stockSubTitle: 'Including HK stocks, US stocks, ETFs',
        fundTitle: 'Fund Market',
        fundSubTitle: 'Including equity, bond, mixed funds etc.',
        cash: 'Cash',
        stockFund: 'Equity Fund',
        bondFund: 'Bond Fund',
        mixtureFund: 'Mixed Fund',
        moneyFund: 'Money Market Fund',
        hkStock: 'HK Stocks',
        usStock: 'US Stocks',
        hkFund: 'HKD Funds',
        usFund: 'USD Funds',
        noStock: 'No stocks added yet',
        noFund: 'No funds added yet',
        addStock: 'Add Stock',
        addFund: 'Add Fund',
        next: 'Next',
        previous: 'Previous',
        limitedTip: 'Please add at least 1 product',
        inputTitle: 'Portfolio Name',
        inputErrorTip: 'Portfolio name contains sensitive words, please re-enter',
        inputPlaceholder: 'Please enter 1-10 characters',
        inputDescription: 'Investment strategy cannot be deleted after creation, only name and description can be modified',
        agreementTip: 'I have read and agree to',
        orderCreateAgreement: 'Portfolio Order Disclaimer',
        and: 'and',
        customerAgreement: 'Client Declaration',
        complete: 'Complete Creation',
        success: 'Created Successfully',
    },
    editCustomerInfo: {
        title: 'Edit Profile',
        personalTags: 'Personal Tags',
        tagTips: 'Select Tags',
        investExps: 'Investment Experience',
        investExpsTips: 'Please select investment experience',
        brief: 'Personal Introduction',
        briefTips: 'Please enter your personal introduction, a good introduction attracts more followers~',
        investIdea: 'Investment Philosophy',
        investIdeaTips: 'Please enter your investment philosophy, e.g. balanced allocation',
        advantage: 'Expertise Areas',
        advantageTips: 'Please enter your expertise areas, e.g. quantitative index enhancement',
        editConfirm: 'Confirm Changes',
        errorMsg: 'Content contains sensitive words, please re-enter',
        lessOneYear: 'Less than 1 year',
        lessSixYears: '1-5 years',
        lessElevenYears: '6-10 years',
        moreThanTenYears: 'Over 10 years',
    },
    addPersonalTags: {
        title: 'Add Personal Tags',
        saved: 'Save',
        noData: 'No Tags',
        tagsSelTip: 'Please select personal tags (maximum 4)',
        maxSelToast: 'Maximum 4 tags can be added',
    },
    followRrderRecordTitle: 'Portfolio Orders',
    wealthRrderRecordTitle: 'Wealth Management Orders',
    notEnoughCash: 'Insufficient cash available, please deposit funds',
    specialAccountService: 'Special Account Service',
    wealthProduct: 'Wealth Management Products',
    observations: 'Observations',
    observationsDate: {
        obsDate: 'Observation Date',
        couponPaymentDate: 'Coupon Payment Date',
        tradingDate: 'Trading Date',
        issueDate: 'Issue Date',
        maturityObsDate: 'Maturity Observation Date',
        settlementEventDate: 'Final Settlement Event',
    },
    ry: {
        protocolTitle: 'Related Agreements and Documents',
    },
    customServiceOutageTip: "This user's Easy Investment service has been suspended by the system, related operations are not available",
    customServiceOutageContactTip:
        'Your Easy Investment service has been suspended by the system. Please contact customer service to restore service',
    subscribeDescText1:
        'T Day: Fund trading day, with {time} as the cutoff time. Orders before {time} are processed on T day, after {time} on T+1 day. Weekends and fund holidays are not trading days. (All times are Hong Kong time)',
    subscribeDescText2: 'Cancellation: You can cancel submitted orders before {time} on T day.',
    redeemDescText1:
        'T Day: Fund trading day, with {time} as the cutoff time. Orders before {time} are processed on T day, after {time} on T+1 day. Weekends and fund holidays are not trading days. (All times are Hong Kong time)',
    redeemDescText2: 'Cancellation: You can cancel submitted orders before {time} on T day.',
    tradeRuleDescTest3: 'Above estimated times are for reference only, subject to actual occurrence time.',
    startAmount: 'Minimum Investment',
    subscribeFee: 'Subscription Fee',
    subscribeStatus: 'Subscription Status',
    canSubscribe: 'Available for Purchase',
    minRedeem: 'Minimum Redemption',
    redeemFee: 'Redemption Fee',
    redeemStatus: 'Redemption Status',
    canRedeem: 'Available for Redemption',
    managerFee: 'Management Fee',
    storageFee: 'Custody Fee',
    buyRate: 'Estimated Fees',
    performanceFee: 'Performance Fee',
    otherFee: 'Other Fees',
    other: 'Other',
    openDerivative: 'Enable Permissions',
    services: 'Exclusive Services',
    servicesManager: 'Dedicated Service Manager',
}
