export default {
    holdProfit: 'Holding Profit',
    holdProfitRate: 'Holding Return Rate',
    latestProfit: 'Latest Profit',
    buyOnWay: 'Pending Buy: ',
    sellOnWay: 'Pending Settlement: ',
    doingOrder: '{num} Orders in Progress',
    holdlingAmount: 'Holding Amount',
    leftDays: 'Days to Maturity',
    estimateProfitloss: 'Estimated Profit',
    holdQuantity: 'Holding Units',
    dailyRiseFall: 'Daily Change',
    holdAveragePrice: 'Average Cost',
    latestNav: 'Latest NAV {date}',
    averageBuyPrice: 'Average Purchase Price',
    wealthHolding: 'Investment Holdings',
    wealthAssets: 'Investment Assets',
    holdingDetailInfo: 'Holding Details',
    clearanceProduct: 'Liquidated Products',
    assetsDetail: 'Asset Details',
    holdingRate: 'Holding Ratio',
    noHoldingToView: 'View Products',
    chooseSort: 'Select Sort Method',
    sortByAmount: 'Sort by Holding Amount',
    sortByLatestProfit: 'Sort by Latest Profit',
    sortByYesterdayProfit: "Sort by Yesterday's Profit",
    sortByHoldingProfit: 'Sort by Holding Profit',
    sortByProfitRate: 'Sort by Return Rate',
    updateStatus: 'Update Status',
    holdingDetail: 'Holding Details',
    expireProfit: 'Estimated Maturity Profit',
    expireProfitSummary: 'Total Estimated Maturity Profit',
    addToBuy: 'Add Investment',
    autoSettle: 'Product will be automatically settled on maturity date, no manual redemption required',
    soldOut: 'This product has been delisted',
    stopSelling: 'This product has suspended sales',
    rangeProfit: 'Period Profit',
    rangeProfitRate: 'Period Return Rate',
    interestIncome: 'Interest Income',
    priceGainIncome: 'Price Gain Income',
    allAssets: 'All Assets',
    assets: 'Assets',
    latestClosePrice: 'Reference Price {date}',
    staticDate: 'Statistics Date: ',
    noOpenCashBox: 'Open Account',
    alreadyClearance: 'Liquidated',
    realizedIncome: 'Realized Profit',
    unrealizIncome: 'Unrealized Profit',
    realizedGain: 'Accrued Interest',
    holdProfitWithRate: 'Holding Profit/Rate',
    profitLossAmount: 'Profit Amount',
    totalHolding: 'Total Holdings',
    holdingCount: 'Holding Quantity',
    netInterestAtMaturity: 'Net Interest at Maturity (After Fees)',
}
